app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$', views.home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^cnycn/', include('cnycn.urls', namespace='cnycn')),
    url(r'^gas/', include('gas.urls', namespace='gas')),
    url(r'^documentos/', include('documentos.urls', namespace='documentos')),
    url(r'^programacionweb/', include('programacionweb.urls', namespace='programacionweb')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Cesar Guillermo Gutierrez Trillo </title>
    <!-- Bootstrap core -->
    {% load staticfiles %}
    <link href="{% static 'app/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <!-- estilo personalizado -->
    <link href="{% static 'app/css/scrolling-nav.css' %}" rel="stylesheet" type="text/css">
</head>

<body id="arriba">
    <!-- navegacion -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#arriba">Inicio</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="#proyectos">Proyectos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="bg-primary text-white">
        <div class="container text-center">
            <h1 style="margin-top: 65px;">Cesar Guillermo Gutierrez Trillo</h1>
            <p class="lead">Mis Proyectos</p>
        </div>
    </header>
    <!-- mosaicos -->
    <section id="proyectos">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="accordian">
                        <ul>
                            <li>
                                <div class="image_title">
                                    <a href="{% url 'cnycn:home' %}">CnyCn</a>
                                </div>
                                <a href="{% url 'cnycn:home' %}">
        <img src="{% static 'app/img/cnycn.png' %}"/>
      </a>
                            </li>
                            <li>
                                <div class="image_title">
                                    <a href="{% url 'gas:home' %}">Modulo de Gasolinas</a>
                                </div>
                                <a href="{% url 'gas:home' %}">
        <img src="{% static 'app/img/gas.png' %}"/>
      </a>
                            </li>
                            <li>
                                <div class="image_title">
                                    <a href="#"></a>
                                </div>
                                <a href="#">
        <img src="http://thcodeplayer.com/uploads/media/00kih8g.jpg"/>
      </a>
                            </li>
                            <li>
                                <div class="image_title">
                                    <a href="#"></a>
                                </div>
                                <a href="#">
        <img src="http://theodeplayer.com/uploads/media/2rT2vdx.jpg"/>
      </a>
                            </li>
                            <li>
                                <div class="image_title">
                                    <a href="#"></a>
                                </div>
                                <a href="#">
        <img src="http://theodeplayer.com/uploads/media/8k3N3EL.jpg"/>
      </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white"></p>
      </div>
    </footer>
    <!-- Bootstrap JavaScript -->
    <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Plugin JavaScript -->
    <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- JavaScript personalizado -->
    <script src="{% static 'app/js/scrolling-nav.js' %}"></script>
</body>

</html>