app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$', views.home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^cnycn/', include('cnycn.urls', namespace='cnycn')),
    url(r'^gas/', include('gas.urls', namespace='gas')),
    url(r'^documentos/', include('documentos.urls', namespace='documentos')),
    url(r'^programacionweb/', include('programacionweb.urls', namespace='programacionweb')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

	url(r'^$', views.home, name = 'home'),
	url(r'^pay$', views.pay_request, name = 'pay_request'),
	url(r'^pay_object/(?P<solicitud>[0-9A-Za-z._%+-]+)$', views.pay_request_object, name = 'pay_object'),
	url(r'^review_object/(?P<solicitud>[0-9A-Za-z._%+-]+)$', views.review_request_object, name = 'review_object'),
	url(r'^cancel_object/(?P<solicitud>[0-9A-Za-z._%+-]+)$', views.cancel_request_object, name = 'cancel_object'),
	url(r'^aprove_object/(?P<solicitud>[0-9A-Za-z._%+-]+)$', views.aprove_request_object, name = 'aprove_object'),
	url(r'^nva_semana$', views.nva_semana, name = 'nva_semana'),
	url(r'^update_kilometraje/(?P<pk>\d+)$', views.update_kilometraje.as_view(), name = 'update_kilometraje'),
	# url(r'^pay_object$', views.pay_request_object, name = 'pay_object'),
	url(r'^rev$', views.rev_request, name = 'rev_request'),
	url(r'^approval$', views.approval_request, name = 'approval_request'),
	url(r'^exito$', views.exito, name = 'exito'),
	url(r'^perfil$', views.PerfilView.as_view(), name = 'perfil'),
	url(r'^solicitud$', views.solicitar_create.as_view(), name = 'solicitud'),
	url(r'^solicitudes$', views.SolicitudesView.as_view(), name = 'solicitudes'),
	url(r'^aprobar/(?P<pk>\d+)$', views.aprobar.as_view(), name = 'aprobar'),
	url(r'^km_recorrer$', views.km_recorrer.as_view(), name = 'km_recorrer'),
	url(r'^listado_generadores$', views.listado_generadores.as_view(), name = 'listado_generadores'),
	url(r'^listado_vehiculos$', views.listado_vehiculos.as_view(), name = 'listado_vehiculos'),
	url(r'^horas_uso$', views.horas_uso.as_view(), name = 'horas_uso'),
	url(r'^nva_semana_generadores$', views.nva_semana_generadores, name = 'nva_semana_generadores'),
	url(r'^update_horas/(?P<pk>\d+)$', views.update_horas.as_view(), name = 'update_horas'),
	url(r'^agregar_generador$', views.agregar_generador.as_view(), name = 'agregar_generador'),
	url(r'^agregar_vehiculo$', views.agregar_vehiculo.as_view(), name = 'agregar_vehiculo'),
	url(r'^estatus_object/(?P<generador>[0-9A-Za-z._%+-]+)$', views.estatus_request_object, name = 'estatus_object'),
	url(r'^estatusVehiculo_object/(?P<vehiculo>[0-9A-Za-z._%+-]+)$', views.estatusVehiculo_request_object, name = 'estatusVehiculo_object'),
	url(r'^update_generadores/(?P<pk>\d+)$', views.update_generadores.as_view(), name = 'update_generadores'),
	url(r'^update_vehiculos/(?P<pk>\d+)$', views.update_vehiculos.as_view(), name = "update_vehiculos"),
	url(r'^saldos$', views.saldos.as_view(), name = 'saldos'),
	url(r'^update_saldos/(?P<pk>\d+)$', views.update_saldos.as_view(), name = "update_saldos"),
	url(r'^reporte_generadores/(?P<pk>\d+)/$', views.reporte_generadores.as_view(), name='reporte_generadores'),
	url(r'^reporte_vehiculos/(?P<pk>\d+)/$', views.reporte_vehiculos.as_view(), name='reporte_vehiculos'),
)

gas/models.py
from django.db import models
from decimal import *
from django.contrib.auth.models import User
from django.utils import timezone
from django.forms.fields import DateField
from django.db.models import Avg, F
# Create your models here.

class Vehiculo(models.Model):

    CAMIONETA = 1
    AUTO = 2
    GENIE = 3
    GRUA = 4
    MANIPULADOR = 5
    TIPO = (
        (CAMIONETA, 'CAMIONETA'),
        (AUTO, 'AUTO'),
        (GENIE, 'GENIE'),
        (GRUA,'GRUA'),
        (MANIPULADOR,'MANIPULADOR'),
    )
    tipo = models.SmallIntegerField(choices=TIPO, verbose_name=('Tipo'), default=CAMIONETA)
    usuario = models.ForeignKey(User)
    marca = models.CharField(max_length=15,blank=True, null=True)
    modelo = models.CharField(max_length=30,blank=True, null=True)
    zona = models.CharField(max_length=15,blank=True, null=True)
    descripcion = models.CharField(max_length=100,blank=True, null=True)
    placa = models.CharField(max_length=15,blank=True, null=True)
    # residente = models.CharField(max_length=25,blank=True, null=True)
    obra = models.CharField(max_length=50,blank=True, null=True)
    anio = models.CharField(max_length=15,blank=True, null=True)
    kilometraje_odometro = models.IntegerField(blank=True, null=True)
    rendimiento = models.DecimalField(max_digits=5,decimal_places=2, blank=True, null=True)
    color = models.CharField(max_length=15,blank=True, null=True)
    status = models.CharField(max_length=20,blank=True,null=True)

    def __unicode__(self):
        return self.modelo

    def get_tipo_display(self):
        tipos = dict(self.TIPO)
        return tipos[self.tipo]

    @property
    def cantidad(self):
        kilometros_vehiculo = Kilometraje.objects.filter(vehiculo_id=self.id).order_by('-id')[:5].aggregate(Avg('kilometraje'))["kilometraje__avg"]
        val = (Decimal(kilometros_vehiculo)/self.rendimiento)* 18
        return val

    @property
    def cantidad_generadores(self):
        horas_prendido = Generadores.objects.filter(generadores_id=self.id).order_by('-id')[:5].aggregate(Avg('kilometraje'))["kilometraje__avg"]
        val = (Decimal(kilometros_vehiculo)/self.rendimiento)* 18
        return val
    

class Perfil(models.Model):
    usuario = models.ForeignKey(User)
    zona_usuario = models.CharField(max_length=15,blank=True,null=True)
    numero_tarjeta = models.CharField(max_length=30, blank=True, null=True)
    banco = models.CharField(max_length=30, blank=True, null=True)
    telefono = models.CharField(max_length=20,null=True)
    edad = models.CharField(max_length=3, null=True)
    is_supervisor = models.BooleanField(blank = True)
    tiene_tarjeta = models.BooleanField(blank=True, default=True)
    saldo_tarjeta = models.DecimalField(blank=True, max_digits=8, decimal_places=2, null=True)


    def __unicode__(self):
        return "%s %s" % (self.usuario.first_name,self.usuario.last_name)



class Solicitud(models.Model):

    SOLICITADO = 1
    REVISION = 2
    APROBADO = 3
    PAGADO = 4
    CANCELADO = 5
    ESTATUS = (
        (SOLICITADO, 'SOLICITADO'),
        (REVISION, 'REVISION'),
        (APROBADO, 'APROBADO'),
        (PAGADO,'PAGADO'),
        (CANCELADO,'CANCELADO'),
    )
    estatus = models.SmallIntegerField(choices=ESTATUS, verbose_name=('Estatus'), default=SOLICITADO)
    usuario = models.ForeignKey(User)
    clave_proyecto = models.CharField(max_length=200,blank=True, null=True)
    justificacion = models.TextField(verbose_name='Justificacion')
    gasolina_troca = models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Gasolina troca', blank=True, null=True)
    gasolina_generador = models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Gasolina generador', blank=True, null=True)
    total = models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Total Solicitado', blank=True, null=True)
    total_aprobado = models.DecimalField(max_digits=8,decimal_places=2,verbose_name='Total Aprobado', blank=True, null=True)
    fecha_solicitud = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_revision = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_aprobacion = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_pago = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    fecha_cancelacion = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    class Meta:
        permissions = (
            ("can_review", "Can review"),
            ("can_approve", "Can approve"),
            ("can_pay", "Can pay"),
            ("can_cancel", "Can cancel"),
            ("can_kilometros", "Can kilometros"),
            ("can_generadores", "Can generadores"),
            ("can_saldos", "Can saldos"),
            )

    def __unicode__(self):
        return '%s' % (self.usuario_id)

    def get_tipo_display(self):
        status = dict(self.ESTATUS)
        return status[self.estatus]

    @property
    def cantidad_sugerida(self):
        usuario_cantidad = Solicitud.objects.filter(usuario=self.usuario).aggregate(Avg('total'))
        return usuario_cantidad

    

class Kilometraje(models.Model):
    vehiculo = models.ForeignKey(Vehiculo)
    kilometraje = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)
    fecha = models.DateField(blank=True, null=True)
    activo = models.BooleanField(blank=True, default=True)
    # @property
    # def promedio(self):
    #     promedio_kilometraje = Kilometraje.objects.values(
    #         'vehiculo_id',
    #         'kilometraje').aggregate(
    #         vehiculo_id=F('vehiculo_id'),
    #         kilometraje=Avg('kilometraje')
    #         )
    #     print promedio_kilometraje


        # gasolina = 18
        # promedio_kilometraje = Kilometraje.objects.filter(vehiculo_id=self.vehiculo_id).aggregate(Avg('kilometraje'))
        # # promedio_kilometraje = Kilometraje.objects.filter(vehiculo_id=self.vehiculo_id)
        # # promedio_kilometraje = Kilometraje.objects.filter(kilometraje=gasolina)
        # print promedio_kilometraje
        # return promedio_kilometraje

    # @property
    # def promedio(self):
        # c = c.annotate(metric=Sum('results__metric'))
        # c = c.annotate(metric_prior=Sum('results__metric_prior'))
        # c = c.annotate(variance=F('metric')-F('metric_prior'))


class Generadores(models.Model):
    descripcion = models.CharField(max_length=50, blank=True, null=True)
    obra = models.CharField(max_length=200,blank=True, null=True)
    estatus = models.CharField(max_length=20,blank=True,null=True)
    fecha_compra = models.DateField(blank=True, null=True)
    serie = models.CharField(max_length=30, blank=True, null=True)
    marca = models.CharField(max_length=30, blank=True, null=True)
    marcador = models.CharField(max_length=15, blank=True, null=True)
    estatus_obra = models.CharField(max_length=30, blank=True, null=True)
    usuario = models.ForeignKey(User)

    def __unicode__(self):
        return self.descripcion

class HorasGeneradores(models.Model):
    generador = models.ForeignKey(Generadores)
    horas_uso = models.IntegerField(blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)

gas/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from gas.models import Solicitud, Vehiculo, Kilometraje, Generadores, Perfil
from django.forms import ModelForm, TextInput
from datetime import datetime
from django.contrib.admin.widgets import AdminDateWidget 
from django.forms.fields import DateField
from django.forms.widgets import Widget


class NvaSemanaForm(forms.Form):
    vehiculo = forms.CharField(required=True)
    kilometraje = forms.CharField(required=True)
    fecha = forms.CharField()


class SolicitudForm(forms.ModelForm):
    usuario = forms.CharField(required=True)
    clave_proyecto = forms.CharField(max_length=200,required=True)
    justificacion = forms.CharField()
    gasolina_troca = forms.DecimalField(max_digits=8,decimal_places=2, required=True)
    gasolina_generador = forms.DecimalField(max_digits=8,decimal_places=2, required=True)
    total = forms.DecimalField(widget=forms.TextInput(attrs={'readonly':'readonly'}), max_digits=8,decimal_places=2, required=True)
    estatus = forms.IntegerField()



class VehiculoForm(forms.ModelForm):
    class Meta:
        model = Vehiculo
        fields = ['marca', 'modelo', 'zona', 'descripcion', 'placa', 'obra', 'anio', 'kilometraje_odometro', 'rendimiento', 'color', 'usuario', 'tipo', 'status']


class KilometrajeForm(forms.ModelForm):
    class Meta:
        model = Kilometraje
        fields = ["kilometraje"]
        widgets = {
            'kilometraje': forms.TextInput(attrs={'class': 'form-control'}),
        }

class GeneradoresForm(forms.ModelForm):
    class Meta:
        model = Generadores
        fields = ['descripcion', 'obra', 'estatus', 'fecha_compra', 'serie', 'marca','marcador','estatus_obra','usuario']


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['saldo_tarjeta']

templates/gas/agregar_generador.html
{% include "gas/base.html" %}

{% block content %}

<div class="container acc-settings">
    <form role="form" action="#" method="post">
        {% csrf_token %}
      <fieldset class="form-group">
        <label>Descripcion</label>
        <input autofocus="autofocus" type="text" class="form-control" id="descripcion" name="descripcion" placeholder="">
      </fieldset>
      <fieldset class="form-group">
        <label>Obra</label>
        <input autofocus="autofocus" type="text" class="form-control" id="obra" name="obra" placeholder="">
      </fieldset>
      <fieldset class="form-group">
        <label>Status</label>
        <select class="form-control" id="estatus" name="estatus">
            <option>Activo</option>
            <option>Inactivo</option>
        </select>
      </fieldset>
      <fieldset class="form-group">
        <label>Fecha de compra</label>
        <input type='date' class="form-control" name='fecha_compra' id='fecha_compra' />
        </select>
      </fieldset>
      <fieldset class="form-group">
        <label>Serie</label>
        <input autofocus="autofocus" type="text" class="form-control" id="serie" name="serie" placeholder="">
      </fieldset>
      <fieldset class="form-group">
        <label>Marca</label>
        <input autofocus="autofocus" type="text" class="form-control" id="marca" name="marca" placeholder="">
      </fieldset>
      <fieldset class="form-group">
        <label>Marcador</label>
        <input autofocus="autofocus" type="text" class="form-control" id="marcador" name="marcador" placeholder="">
      </fieldset>
      <fieldset class="form-group">
        <label>Estatus en Obra</label>
        <input autofocus="autofocus" type="text" class="form-control" id="estatus_obra" name="estatus_obra" placeholder="">
      </fieldset>
      <fieldset class="form-group">
        <label>Usuario Resguardo</label>
        {{ form.usuario }}
      </fieldset>
      <button type="submit" class="btn btn-primary">Enviar</button>
      <button type="reset" class="btn btn-primary" onclick="location.href='{% url 'gas:horas_uso' %}'">Cancelar</button>
    </form>
</div>
<style>
.acc-settings {
    max-width: 600px;
    padding-top: 70px;
}
</style>

<script>
    // codigo para poner el datepicker en español
    $.datepicker.regional['es'] = {
        dateFormat: 'yy-mm-dd',
        closeText: 'Cerrar',
        prevText: '< Ant',
        nextText: 'Sig >',
        currentText: 'Hoy',
        monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
        dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Juv', 'Vie', 'Sáb'],
        dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'],
        weekHeader: 'Sm',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''
    };
    // funcion javascript para el datepicker
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $(function () {
        $(".datepicker").datepicker();
    });
</script>

{% endblock %}

templates/gas/generic.html
<!DOCTYPE html>
<html>
<head>
	<title>Update</title>
</head>
<body>
	<h1></h1>
	<form role = "form" action="#" method="post">
		<ul>

		</ul>
	</form>

</body>
</html>

templates/gas/solicitudes.html
{% include "gas/base.html" %}


<style>th.dt-center, td.dt-center { text-align: center; }

  .modal-header, h4, .close {
      background-color: #5cb85c;
      color:white !important;
  }
  .modal-footer {
      background-color: #f9f9f9;
  }
  </style>



{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h3 style="margin-top:7%; margin-left:1%;" class="page-header">Tus Solicitudes</h3>



    </div>    
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-info">

            <div class="panel-body">
                <div class='form-group'>
                    <div class="row">                 
                        <div class="col-lg-3">    
                                                                                 
                        </div>
                        <div style="float:center;" class="col-lg-7">

                        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal_revisar">Revisar Todo</button>

                        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal_approve">Aprobar Todo</button>

                        <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal_pay">Pagar Todo</button>

                        <!--{% if perms.gas.can_cancel %}
                        <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#myModal_cancel">Cancelar Todo</button>
                        {% endif %}
                        </div>-->   
                        </div>

                       <div id="myModal_pay" class="modal fade" role="dialog">
                         <div class="modal-dialog">

                        <!-- Modal content-->
                            <div class="modal-content">
                             <div class="modal-header">
                             <button type="button" class="close" data-dismiss="modal">&times;</button>
                             <h4 class="modal-title"></h4>
                            </div>
                             <div class="modal-body">
                                    <p>Todas las solicitudes en estatus APROBADO pasaran a estatus PAGADO</p>
                            </div>
                                    <div class="modal-footer">
                                         <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                         <button type="button" onclick="location.href='{% url 'gas:pay_request' %}'" class="btn btn-success" data-dismiss="modal">Aceptar</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="myModal_revisar" class="modal fade" role="dialog">
                         <div class="modal-dialog">

                        <!-- Modal content-->
                            <div class="modal-content">
                             <div class="modal-header">
                             <button type="button" class="close" data-dismiss="modal">&times;</button>
                             <h4 class="modal-title"></h4>
                            </div>
                             <div class="modal-body">
                                    <p>Todas las solicitudes en estatus SOLICITADO pasaran a estatus REVISADO</p>
                            </div>
                                    <div class="modal-footer">
                                         <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                         <button type="button" onclick="location.href='{% url 'gas:rev_request' %}'" class="btn btn-success" data-dismiss="modal">Aceptar</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" id="myModal_approve" role="dialog">
                            <div class="modal-dialog">
                        <!-- contenido del modal-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Todas las solicitudes en estatus REVISADO pasaran a estatus APROBADO</p>
                                    </div>
                                    <div class="modal-footer">
                                         <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                         <button type="button" onclick="location.href='{% url 'gas:approval_request' %}'" class="btn btn-success" data-dismiss="modal">Aceptar</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="modal fade" id="myModal_cancel" role="dialog">
                            <div class="modal-dialog">
                        <!-- contenido del modal-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Todas las solicitudes se cancelaran. Solo puede cancelar las solicitudes en estatus SOLICITADO</p>
                                    </div>
                                    <div class="modal-footer">
                                         <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                         <button type="button" onclick="location.href=''" class="btn btn-success" data-dismiss="modal">Aceptar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <table id="tabla" class="table table-striped table-bordered" cellspacing="0" style="font-size:12px;" >
                            <thead>
                                <tr>
                                    <th class="text-center">Cantidad Solicitada</th>
                                    <th class="text-center">Cantidad sugerida</th>
                                    <th class="text-center">Cantidad Aprobada</th>
                                    <th class="text-center">Nombre del Solicitante</th>
                                    <th class="text-center">Justificacion</th>
                                    <th class="text-center">Tarjeta</th>
                                    <th class="text-center">Fecha de Solicitud</th>
                                    <th class="text-center">Estatus</th>

                                    <th class="text-center">Revisar</th>

                                    <th class="text-center">Aprobar esta cantidad</th>


                                    <th class="text-center">Aprobar cantidad diferente</th>


                                    <th class="text-center">Pagar</th>


                                    <th class="text-center">Cancelar</th>



                                </tr>
                            </thead>

                            <tbody>
                            {% for solicitud in object_list %}
                                <tr>
                                    <td>${{ solicitud.total }}</td>
                                    <td>{%for vehiculo in solicitud.usuario.vehiculo_set.all%} ${{vehiculo.cantidad | floatformat:2 }}{% endfor %} </td>
                                    <td>${{ solicitud.total_aprobado|default_if_none:"&nbsp;" }}</td>
                                    <td><a data-toggle="modal" href="#{{ solicitud.usuario.pk }}" data-id="5">{{ solicitud.usuario.first_name}} {{solicitud.usuario.last_name}}</a></td>
                                    <td>Proyecto:  {{ solicitud.clave_proyecto }}</br> </br> {{ solicitud.justificacion }}</td>
                                    {% for perfiles in solicitud.usuario.perfil_set.all %}
                                    <td>{{ perfiles.numero_tarjeta }}</td>
                                    {% endfor %}
                                    <td>{{ solicitud.fecha_solicitud.year }}/{{ solicitud.fecha_solicitud.month }}/{{ solicitud.fecha_solicitud.day }}</td>
                                    <td>{{ solicitud.get_tipo_display }}</td>

                                    <td align="center"><a href="{% url 'gas:review_object' solicitud.id %}"><i class="fa fa-check-square-o"></i></a></td>

                                    <td align="center"><a href="{% url 'gas:aprove_object' solicitud.id %}"><i class="fa fa-thumbs-o-up"></i></a></td>


                                    <td align="center"><a href="{% url 'gas:aprobar' solicitud.id %}"><i class="fa fa-thumbs-o-up"></i></a></td>


                                    <td align="center"><a href="{% url 'gas:pay_object' solicitud.id %}"><i class="fa fa-dollar"></a></td>


                                    <td align="center"><a href="{% url 'gas:cancel_object' solicitud.id %}"><i class="fa fa-close"></a></td>


                                    <!--modal perfiles -->
                                    <div class="modal fade" id="{{ solicitud.usuario.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Perfil del Usuario {{ solicitud.usuario.pk }}</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                </div>
                                            <div class="modal-body">
                                                {% for perfiles in solicitud.usuario.perfil_set.all %}
                                                <label>EDAD:</label>
                                                <strong><p>{{ perfiles.edad }}</p></strong>
                                                <label>BANCO:</label>
                                                <strong><p>{{ perfiles.banco }}</p></strong>
                                                <label>TELEFONO:</label>
                                                <strong><p>{{ perfiles.telefono }}</p></strong>
                                                <label>NUMERO DE TARJETA:</label>
                                                <strong><p>{{ perfiles.numero_tarjeta }}</p></strong>
                                                <label>ZONA DEL USUARIO:</label>
                                                <strong><p>{{ perfiles.zona_usuario }}</p></strong>
                                                {% endfor %}
                                            </div>
                                         <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                        </div>
                                            </div>
                                        </div>
                                        </div>
                                    <!-- termina modal -->
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block scripts %}



<script>


$(document).ready(function() 
{

    var table = $('#tabla').DataTable({
        responsive: true,
        colReorder: true,
        "order": [[ 6, "desc" ]],
        bLengthChange: true,
        dom: 'lfBrtip',
        buttons: [  
            {
                extend: 'pdfHtml5',
                orientation: 'landscape',
                pageSize: 'LEGAL',

            },
            {
                extend: 'excelHtml5',
                exportOptions: {
                    columns: ':visible'
                }
            },
            'colvis',
        ],
        "pageLength": 50,
         "columnDefs": [
         { className: "dt-center", "targets": [ 0 ] }
         ],

        "language": {
            url: "/static/app/localizacion/es_ES.json"
        }
    } );

  
    $('#tabla tbody').on( 'click', 'tr', function() 
    {
        if ($(this).hasClass('selected') ) 
        {           
            $(this).removeClass('selected');
             
        }
        else 
        {
            table.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');                      
        }
    });
     
});

</script>
{% endblock %}